// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package entity

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson163c17a9DecodeWeatherbotEntity(in *jlexer.Lexer, out *WeatherCastError) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "cod":
			out.ResponseCode = int(in.Int())
		case "message":
			out.Message = string(in.String())
		case "Params":
			if in.IsNull() {
				in.Skip()
				out.Params = nil
			} else {
				in.Delim('[')
				if out.Params == nil {
					if !in.IsDelim(']') {
						out.Params = make([]string, 0, 4)
					} else {
						out.Params = []string{}
					}
				} else {
					out.Params = (out.Params)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Params = append(out.Params, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson163c17a9EncodeWeatherbotEntity(out *jwriter.Writer, in WeatherCastError) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cod\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ResponseCode))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"Params\":"
		out.RawString(prefix)
		if in.Params == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Params {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WeatherCastError) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson163c17a9EncodeWeatherbotEntity(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WeatherCastError) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson163c17a9EncodeWeatherbotEntity(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WeatherCastError) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson163c17a9DecodeWeatherbotEntity(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WeatherCastError) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson163c17a9DecodeWeatherbotEntity(l, v)
}
func easyjson163c17a9DecodeWeatherbotEntity1(in *jlexer.Lexer, out *WeatherCast) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "coord":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Coord = make(map[string]float64)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v4 float64
					v4 = float64(in.Float64())
					(out.Coord)[key] = v4
					in.WantComma()
				}
				in.Delim('}')
			}
		case "main":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Main = make(map[string]float64)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v5 float64
					v5 = float64(in.Float64())
					(out.Main)[key] = v5
					in.WantComma()
				}
				in.Delim('}')
			}
		case "wind":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Wind = make(map[string]float64)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v6 float64
					v6 = float64(in.Float64())
					(out.Wind)[key] = v6
					in.WantComma()
				}
				in.Delim('}')
			}
		case "cod":
			out.ResponseCode = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson163c17a9EncodeWeatherbotEntity1(out *jwriter.Writer, in WeatherCast) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"coord\":"
		out.RawString(prefix[1:])
		if in.Coord == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v7First := true
			for v7Name, v7Value := range in.Coord {
				if v7First {
					v7First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v7Name))
				out.RawByte(':')
				out.Float64(float64(v7Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"main\":"
		out.RawString(prefix)
		if in.Main == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v8First := true
			for v8Name, v8Value := range in.Main {
				if v8First {
					v8First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v8Name))
				out.RawByte(':')
				out.Float64(float64(v8Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"wind\":"
		out.RawString(prefix)
		if in.Wind == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v9First := true
			for v9Name, v9Value := range in.Wind {
				if v9First {
					v9First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v9Name))
				out.RawByte(':')
				out.Float64(float64(v9Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"cod\":"
		out.RawString(prefix)
		out.Int(int(in.ResponseCode))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WeatherCast) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson163c17a9EncodeWeatherbotEntity1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WeatherCast) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson163c17a9EncodeWeatherbotEntity1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WeatherCast) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson163c17a9DecodeWeatherbotEntity1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WeatherCast) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson163c17a9DecodeWeatherbotEntity1(l, v)
}
func easyjson163c17a9DecodeWeatherbotEntity2(in *jlexer.Lexer, out *ForecastUnit) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "dt":
			out.Dt = int64(in.Int64())
		case "main":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Main = make(map[string]float64)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v10 float64
					v10 = float64(in.Float64())
					(out.Main)[key] = v10
					in.WantComma()
				}
				in.Delim('}')
			}
		case "wind":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Wind = make(map[string]float64)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v11 float64
					v11 = float64(in.Float64())
					(out.Wind)[key] = v11
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson163c17a9EncodeWeatherbotEntity2(out *jwriter.Writer, in ForecastUnit) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"dt\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Dt))
	}
	{
		const prefix string = ",\"main\":"
		out.RawString(prefix)
		if in.Main == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v12First := true
			for v12Name, v12Value := range in.Main {
				if v12First {
					v12First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v12Name))
				out.RawByte(':')
				out.Float64(float64(v12Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"wind\":"
		out.RawString(prefix)
		if in.Wind == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v13First := true
			for v13Name, v13Value := range in.Wind {
				if v13First {
					v13First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v13Name))
				out.RawByte(':')
				out.Float64(float64(v13Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ForecastUnit) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson163c17a9EncodeWeatherbotEntity2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ForecastUnit) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson163c17a9EncodeWeatherbotEntity2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ForecastUnit) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson163c17a9DecodeWeatherbotEntity2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ForecastUnit) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson163c17a9DecodeWeatherbotEntity2(l, v)
}
func easyjson163c17a9DecodeWeatherbotEntity3(in *jlexer.Lexer, out *Forecast) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ResponseCode":
			out.ResponseCode = int(in.Int())
		case "List":
			if in.IsNull() {
				in.Skip()
				out.List = nil
			} else {
				in.Delim('[')
				if out.List == nil {
					if !in.IsDelim(']') {
						out.List = make([]*ForecastUnit, 0, 8)
					} else {
						out.List = []*ForecastUnit{}
					}
				} else {
					out.List = (out.List)[:0]
				}
				for !in.IsDelim(']') {
					var v14 *ForecastUnit
					if in.IsNull() {
						in.Skip()
						v14 = nil
					} else {
						if v14 == nil {
							v14 = new(ForecastUnit)
						}
						(*v14).UnmarshalEasyJSON(in)
					}
					out.List = append(out.List, v14)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson163c17a9EncodeWeatherbotEntity3(out *jwriter.Writer, in Forecast) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ResponseCode\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ResponseCode))
	}
	{
		const prefix string = ",\"List\":"
		out.RawString(prefix)
		if in.List == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v15, v16 := range in.List {
				if v15 > 0 {
					out.RawByte(',')
				}
				if v16 == nil {
					out.RawString("null")
				} else {
					(*v16).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Forecast) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson163c17a9EncodeWeatherbotEntity3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Forecast) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson163c17a9EncodeWeatherbotEntity3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Forecast) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson163c17a9DecodeWeatherbotEntity3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Forecast) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson163c17a9DecodeWeatherbotEntity3(l, v)
}
