version: '3.9'
services:
  postgres:
    image: postgres:14.8-alpine3.18
    container_name: postgres_container
    ports:
      - 5430:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      - ../migrations:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - default

    
volumes:
  pgdata:
